from enum import StrEnum


class PhotoView(StrEnum):
    FRONT = "FRONT"
    CAT_LEFT_FRONT_45 = "CAT_LEFT_FRONT_45"
    CAT_RIGHT_FRONT_45 = "CAT_RIGHT_FRONT_45"


class PartLabel(StrEnum):
    BODY = "BODY"
    HEAD = "HEAD"
    SCREEN_LEFT_FRONT_PAW = "SCREEN_LEFT_FRONT_PAW"
    SCREEN_RIGHT_FRONT_PAW = "SCREEN_RIGHT_FRONT_PAW"
    TAIL = "TAIL"
    EYES = "EYES"


class ProjectStatus(StrEnum):
    UPLOADED = "UPLOADED"
    PROCESSING = "PROCESSING"
    LAYER_REVIEW = "LAYER_REVIEW"
    BEAD_REVIEW = "BEAD_REVIEW"
    READY = "READY"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class JobStatus(StrEnum):
    QUEUED = "QUEUED"
    SUBMITTING = "SUBMITTING"
    SUBMIT_UNKNOWN = "SUBMIT_UNKNOWN"
    WAITING_PROVIDER = "WAITING_PROVIDER"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"

